component/authentication-endpoint/src/main/webapp/smsotp.jsp, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
Show the first/last n number of digits of mobile number in UI
Show the first/last n number of digits of mobile number in UI
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
=> Show the first/last n number of digits in UI

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
Show the screenValue in the UI for erroneous scnarios
Pass the screenValue in the redirect url for the erroneous scnarios
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
JDK 1.8
Ubuntu
=> Show the screenValue in the UI for erroneous scenarios

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
When invalid SMS URL is given for SMS OTP configuration log error log is shown. But no feedback is given via the UI.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to …
=> Fix to properly handle invalid SMS URL

pom.xml
Apache Standard Taglibs before 1.2.3 allows remote attackers to execute arbitrary code or conduct external XML entity (XXE) attacks via a crafted XSLT extension in a (1) <x:parse> or (2) <x:transform> JSTL XML tag. 
[CVE-2015-0254](https://nvd.nist.gov/vuln/detail/CVE-2015-0254)
This is fixed by updating the jstl version.
> Brief description of the new feature or bug fix …
=> Change jstl library to fix security vulnerabilities

component/authenticator/pom.xml, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPUtils.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/internal/SMSOTPAuthenticatorServiceComponent.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/internal/SMSOTPServiceDataHolder.java, docs/config.md, pom.xml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Fixed the code to send the otp to the federated mobile claim

component/authenticator/pom.xml, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/internal/SMSOTPAuthenticatorServiceComponent.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/internal/SMSOTPServiceDataHolder.java, pom.xml
> SMS OTP was refactored to use the CEP notification sende.
=> Notification Refactor

docs/config.md
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> doc updated to v2.016

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
Resolves https://github.com/wso2/product-is/issues/4713
=> Null check before write the payload value to the output stream

component/authentication-endpoint/pom.xml, component/authenticator/pom.xml, docs/config.md, feature/pom.xml, pom.xml
> Part of https://github.com/wso2/product-is/issues/5315
> Remove extension util embedded dependency and use OSGi module
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> …
=> Remove extension util embedded dependency and use OSGi module

component/authentication-endpoint/src/main/webapp/WEB-INF/web.xml, pom.xml
=> Add java 11 support

component/authentication-endpoint/src/main/webapp/WEB-INF/web.xml
> Skip annotation scanner for web apps
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Skip annotation scanner for web apps

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
Uncommented the previous code in order to work the expected feature to send SMS notification over CEP
> Link(s) to product …
=> Uncommented the previous code in order to work the expected feature.

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
> Fix build failure issue happened due to introducing of a new constant in current framework
=> Fixed the compilation error without upgrading framework

component/authentication-endpoint/src/main/webapp/smsotp.jsp
- Fixes wso2/product-is#6108.
- Handle the login form submission via jquery
- Store the first submission status as the element's data value via jquery
- For subsequent submissions identified via the above data value, ignore the form submit event
- N/A
=> [SMS OTP Authentication Endpoint] Handle Double Submit In The Login Forum

component/authentication-endpoint/src/main/webapp/smsotp.jsp
- Fixes wso2/product-is#6108.
- Handle the login form submission via jquery
- Store the first submission status as the element's data value via jquery
- For subsequent submissions identified via the above data value, ignore the form submit event
- N/A
=> [5.6/5.8][SMS OTP Authentication Endpoint] Handle Double Submit In The Login Forum

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
Resolves: https://github.com/wso2/product-is/issues/6713
=> Fix NoClassDefFoundError when using org.apache.catalina.util.URLEncoder

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java, pom.xml
Fix the issue with backup codes in sms otp authneticator
=> Fix the issue with backup codes in sms otp authneticator

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
Fix comments in this PR https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/76
=> Fix comments

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java
Fix the issue with backup codes in sms otp authenticator 
Backport this PR https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/76
=> Fix the issue with backup codes in sms otp authenticator

component/authentication-endpoint/pom.xml, component/authenticator/pom.xml, feature/pom.xml, pom.xml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Bump version

component/authentication-endpoint/src/main/webapp/smsotpError.jsp, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPUtils.java, component/authenticator/src/main/resources/ServerClientErrorMappings.properties
Fix https://github.com/wso2/product-is/issues/7569
=> Handle EmailOTP error response using internal errorcodes

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPUtils.java
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Change useInternalErrorCode config

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
Resolves the issue https://github.com/wso2/product-is/issues/7853
=> Fix ClassCastException when TokenExpiryTime configured

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
Fixes https://github.com/wso2/product-is/issues/7853
=> Fix ClassCastException when enabling TokenExpiryTime config in sms-otp authenticator

pom.xml
> Remove unwanted library of jline library.
> Remove unwanted library of jline library.
=> Remove unwanted library of jline.

component/authenticator/pom.xml, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPUtils.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/internal/SMSOTPAuthenticatorServiceComponent.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/internal/SMSOTPServiceDataHolder.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java, pom.xml
Improve account lock for SMS OTP
=> Improve account lock for SMS OTP

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java
Support account locking feature for backup codes
=> Support account locking feature for backup codes

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java
Backport https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/94
=> Support account locking for backup code mismatch

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
Resolves https://github.com/wso2/product-is/issues/8600
https://github.com/wso2-support/identity-apps/pull/18
=> Redirect to error page when user account get locked

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
Fix https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/97/files/cf56b4e891de28aa3090c26a8ecc79c6bfdd1b38#r482612403 comment in PR: https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/97
=> Fix review comments 

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
$subject
Old PR: https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/103
=> Resolve Formating Issue of $originBranch PR

component/authenticator/pom.xml, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java, pom.xml
Add events for email otp generate and validate flows.
Fix for wso2/product-is#10706
As soon as possible
=> Add events for SMS otp related scenarios

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
Fixing NPE caused when user doesn't have the mobile number configured in the profile
=> Fixing NPE caused when user doesn't have the mobile number configured in the profile

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPUtils.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java
Resolves below issue:
https://github.com/wso2/product-is/issues/10819
=> Improvements related to user friendly error message display.

pom.xml
The following dependency packed unwanted jars to the webapplications, thus the size of the webapplication increased to 78.9MB from 5.7MB. 
```
<dependency>
<groupId>org.wso2.carbon.identity.event.handler.accountlock</groupId>
<artifactId>org.wso2.carbon.identity.handler.event.account.lock</artifactId>
<version>${carbon.identity.account.lock.handler.version}</version>
</dependency>
```
Hence, provide the dependency at runtime with the scope element.
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up …
=> Avoid packing unwanted jars to the war file

pom.xml
=> Change framework version range

component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/SMSOTPService.java, component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/SMSOTPServiceImpl.java, component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/constant/Constants.java, component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/dto/GenerationResponseDTO.java, component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/dto/SessionDTO.java, component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/dto/ValidationResponseDTO.java, component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/exception/SMSOTPClientException.java, component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/exception/SMSOTPException.java, component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/exception/SMSOTPServerException.java, component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/internal/SMSOTPServiceComponent.java, component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/internal/SMSOTPServiceDataHolder.java, component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/util/OneTimePasswordUtils.java, component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/util/Utils.java
Refactored code to adhere to WSO2 coding style.
=> Refactored code SMS OTP as a service

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
$subject
Fixes -[ #11583](https://github.com/wso2/product-is/issues/11583)
=> Fix NPE can be occurred in SMS OTP with NEXMO as SMS sender

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
> Solves https://github.com/wso2/product-is/issues/12555 allowing to have a fully customized SMS text.
> Provided a new variable called `$ctx.otp` in addition to the current varibled `$ctx.msg` because `$ctx.msg` is having a hard coded text. Kept the existing `$ctx.msg` to have backward compatibility.
Example HTTP Payload
```
{"to":"$ctx.num","msg":"$ctx.otp is your OTP for WSO2 Portal."}
```
The actual request
```
{"to":"1234567890","msg":"652981 is your OTP for WSO2 Portal."}
```
> WIP
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated …
=> Add support for fully customized SMS with $ctx.otp

component/authenticator/pom.xml, feature/pom.xml, pom.xml
Change the version to 3.0.18-SNAPSHOT
Change the scm tag
=> Change the version to SNAPSHOT

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
Resolves https://github.com/wso2/product-is/issues/13217
In the SMS OTP authenticator, the header values are separated by splitting with a colon Hence, when the header value is having a colon, the latter part is dropped from the value.
```
Header1 : Value1 -> value will be, Value1
Header2 : http://localhost/ - value will be http
```
This PR fixes the issue.
`Header2 : http://localhost/ - value will be http://localhost/ `
> …
=> Improve the support to have colon character in the Header value

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
* $subject
* Fix https://github.com/wso2/product-is/issues/13651
=> Update account locked reason claim when max otp attempts exceed

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
* $subject
* Fix https://github.com/wso2/product-is/issues/13651
=> [3.0.x] Update account locked reason claim when max otp attempts exceed

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPUtils.java
Address review comments on the following PR.
- [https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/127](https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/127)
=> Addressing comments of merged PRs

component/authenticator/setup.txt, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPUtilsTest.java
> Refactor SMS OTP path with path updated with https://github.com/wso2/identity-apps/pull/3113/files
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes …
=> Refactor SMS OTP path

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
=> Add default timeout for sms otp code

component/authenticator/pom.xml, component/common/pom.xml, feature/pom.xml, pom.xml
=> Bump kernel version

component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java
> Fix some of the formatting issues introduced in https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/121.
=> Fix formatting issues

.github/workflows/pr-builder.yml, README.md, component/authenticator/pom.xml, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPUtilsTest.java, component/common/pom.xml, feature/pom.xml, pom.xml
Update mockito 1 to mockito 2 to support JDK 11 and JDK 17 compilation.
After this PR is merged to the main branch, we can't build the branch on JDK 8
https://github.com/wso2/product-is/issues/14224
=> Support JDK 11 and JDK 17 Compilation

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
> Add error log for unexpected http response when sending sms
> Solves issue : https://github.com/wso2/product-is/issues/14846
=> Add error logs for error while sending sms

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
When the `showAuthFailureReason` is set to true, it's expected to show an error message, when the account is locked. This works fine when only the SMS OTP is configured in the second step. However, when it's configured with any other authenticator (ex: Email OTP), it allows the user to try SMS OTP continuously and an error page is not shown.
- https://github.com/wso2/product-is/issues/14868
- https://github.com/wso2-support/identity-apps/pull/242
- https://github.com/wso2-support/carbon-identity-framework/pull/2442
=> [U2][5.11.0] Fix SMS OTP account locked error not shown when configured with multi options

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java, pom.xml
Fixes https://github.com/wso2/product-is/issues/14965
=> Fix Authentication with SAAS app in super-tenant using another tenant's user with SMS-OTP as 2nd factor

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
Related issue: https://github.com/wso2/product-is/issues/14965
=> [U2] [5.11.0] Fix Authentication with SAAS app in super-tenant using another tenant's user with SMS-OTP as 2nd factor

component/authenticator/pom.xml, component/common/pom.xml, feature/pom.xml, pom.xml
Bump POM versions to major version: 4.0.0 for IPK product.
=> Bump pom version to major version

.github/workflows/pr-builder.yml, README.md, component/authenticator/pom.xml, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPUtilsTest.java, component/common/pom.xml, feature/pom.xml, pom.xml
Get latest changes from master for IPK
=> Rebase 4.0.x branch with master

pom.xml
=> Bump Kernel Version 

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
Port the improvement done in https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/117 https://github.com/wso2/product-is/issues/12555 to 2.0.16.x
=> [2.0.16.x] Add support for fully customized SMS with $ctx.otp

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
Port the improvement done in https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/117 https://github.com/wso2/product-is/issues/12555 to 2.0.x
=> [2.0.x] Add support for fully customized SMS with $ctx.otp

.github/workflows/pr-builder.yml, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
Related issue https://github.com/wso2/product-is/issues/16252
=> Provide going back to multi-option page from SMS OTP authenticator

pom.xml
=> Override distributionManagement repo URLs to use https

pom.xml
=> [IS-KM 5.6] Remove log4j and replace with log4j-over-slf4j

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java, component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java, component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java
Support sms OTP for the API Based Authentication
=> Support sms OTP for the API Based Authentication

pom.xml
Change distribution urls to fix build failures
=> Change distribution urls

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
- context.isRetrying() is set to true from the previous failed authenticator.
- If the current authenticator set in the context is different than SMS OTP, then context.isRetrying() can be reset considering this is the first time the authentication flow is entering the sms OTP authenticator.
https://github.com/wso2/product-is/issues/21823
- https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/182
=> Fix NPE in SMSOTP Authenticator when context.isRetrying() is true

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
This PR addresses two issues related to SMS OTP expiry time configuration:
1. Millisecond Conversion Issue:
This PR improves the getSMSOTPExpiryTime method to handle expiry times in milliseconds. Key updates include:
2. Return Type Update: Changed the return type from int to long for millisecond precision.
Configuration Conversion: Added logic to convert expiry time configured in seconds in the toml file to milliseconds.
Related issue:
- https://github.com/wso2/product-is/issues/22231
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file …
=> Improve SMS OTP Expiry Time handling with Millisecond precision 

.connector-store/meta.json
=>  [SMS-OTP] Release 5.10 connector

.connector-store/meta.json
=> Add retired label to connector store

.github/workflows/pr-builder.yml
${Subject} 
- https://github.com/wso2/product-is/issues/23500
=> Bump actions/cache version to v4
