wso2-extensions/identity-outbound-auth-sms-otp

component/authentication-endpoint/src/main/webapp/smsotp.jsp
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java

When show the screenAttribute value in the UI, it shows "null" if the screenValue is returned as null in the request.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
JDK 1.8
ubuntu

Fixed issue when screenValue is returned as null in the requst

---

pom.xml

(cherry picked from commit 30df3b4)
> There are new jars added in the lib which caused to increase the pack size to 60 MB.

Remove additional libraries

---

component/authentication-endpoint/pom.xml
pom.xml

Resolved bellow error
[2019-08-02 10:34:33,801] ERROR {org.apache.catalina.core.StandardWrapperValve} -  Servlet.service() for servlet [jsp] in context with path [/smsotpauthenticationendpoint] threw exception [The absolute uri: http://java.sun.com/jsp/jstl/fmt cannot be resolved in either web.xml or the jar files deployed with this application] with root cause
org.apache.jasper.JasperException: The absolute uri: http://java.sun.com/jsp/jstl/fmt cannot be resolved in either web.xml or the jar files deployed with this application
at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:56)
at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:445)
at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:117)
at …

Fix jstl issue of by providing correct dependencies

---

component/authentication-endpoint/pom.xml
component/authentication-endpoint/src/main/webapp/mobile.jsp
component/authentication-endpoint/src/main/webapp/smsotp.jsp
component/authentication-endpoint/src/main/webapp/smsotpError.jsp
pom.xml

This is to avoid packing of jstl package to the internal WEB_INF/lib folder

Remove jstl dependencies and usages as localization is not used.

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPUtils.java
component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java

Backport of https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/91
Account locking for SMS OTP was already included in this branch. Fixed the issues and improve the code according to the master branch.

Improve account locking feature for SMS OTP

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java

This PR will fix the issue when URL encoding the POST body passing to the SMS gateway causes failing the requests sent to SMS providers.
Resolves: https://github.com/wso2/product-is/issues/9727
Here the encoding of the mobile number is decided upon below two points.
- Content-Type header if present
- HTTP method
If the content-type is application/json and the HTTP method is POST, we will not do the URL encoding of the mobile number.

Fix issue of including leading plus sign in phone number in SMSOTP

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java

This PR will fix the issue of failing the sending requests to SMS providers when URL encoding the POST body passing to the SMS gateway. 
Resolves: https://github.com/wso2/product-is/issues/9727
Proactive fix of https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/101 
Here the encoding of the mobile number is decided upon below two points.
- Content-Type header if present
- HTTP method
So if the content-type is application/json then it will not do the URL encoding the POST body passing to the SMS gateway.

Fix issue when including leading plus sign in phone number in SMSOTP

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java

Partial Fix for : https://github.com/wso2/product-is/issues/10532
Logic : 
- Added two idp configurations in sms otp connector.
- Error Regex
- Error message for validation
Both strings will be sent to jsp page as encoded and validation will be handled in JSP pages, not in SMS OTP authenticator.
Please check the naming before  Approve the PR

Validate added mobile number corresponding to SMS gateway

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java

In the current implementation when multi step authentication is enabled and if the user has not specify the mobile number in the profile, it will prompt user to enter mobile number and then directly saves it. If user enters an
incorrect mobile there is no way for the user to change it himself. This implementation will save the mobile number once it is confirmed with the OTP code sends.
Resolves https://github.com/wso2/product-is/issues/10786

Save mobile number after verifying the mobile number in multi step authentication

---

component/authentication-endpoint/src/main/webapp/smsotpError.jsp
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java

Resolves: wso2/product-is#8600 
Backported https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/97 and https://github.com/wso2-support/identity-apps/pull/18/

Prompt an error page when user account is locked

---

component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/SMSOTPServiceImpl.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/util/Utils.java

Change hashing algorithm to SHA-256
Removed OTP response from the SMS OTP generation request when notifications are handled by the Identity Server.

Change hashing algo and remove OTP from response

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java

Fixing issue [1]. When user doesn't have mobile number configured in user store, SMSOTP workflow requested the mobile number at the login but doesn't show the screen attribute (masked mobile number user entered) when _OTP code view_ is prompted.
Fix is to retrieve the `requested mobile` from the authentication context if the user doesn't have the mobile number configured.
[1] https://github.com/wso2/product-is/issues/13150

Return requested mobile from context for SMSOTP if user doesn't have mobile

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPUtils.java

his PR will resolve the issue of URL encoding of the payload of SMS OTP irrespective of the content type.
With this fix, the payload will be encoded based on the content type. To provide backward compatibility the encoding based on content type will be enabled via a configuration. By default encoding based on the content-type will be enabled, which means content-type based encoding will be performed. To disable encoding the following configuration need to be added to `deployment.toml`.
```
[authentication.authenticator.sms_otp.parameters]
enable_payload_encoding_for_sms_otp = true
```
here payload encoding will be performed as below.
- `text/xml;charset=UTF-8` content type will be XML encoded using `org.owasp.encoder` library.
- `application/json` content type will be parsed using …

Payload encoding in sms otp public

---

README.md
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/SMSOTPServiceImpl.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/constant/Constants.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/dto/ConfigsDTO.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/dto/FailureReasonDTO.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/dto/SessionDTO.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/util/Utils.java
component/common/src/test/java/org/wso2/carbon/identity/smsotp/common/test/UtilsTest.java

SMS OTP Service does not invalidate issued OTP values in multiple failed validation attempts.
Store the no. of failed validation attempts as a new attribute in the session object and insert a new entry to the session store(IDN_AUTH_SESSION_STORE table) with the updated session object each time a validation request is sent until the maximum allowed validation attempts are passed. The maximum allowed validation attempts count is made configurable via deployment.toml file as shown in the example below.
```
[[event_handler]]
name= "smsOtp"
properties.enabled=true
properties.maxValidationAttemptsAllowed=4
```
Resolves git issue: https://github.com/wso2/product-is/issues/13291

Invalidate sms-otp for multiple failed validations

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java

> Use StringUtils trimToEmpty for trimming to avoid NPE
Resolves [product-is #13552](https://github.com/wso2/product-is/issues/13552)

[5.11.0][U2] Use StringUtils trimToEmpty for trimming to avoid NPE

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java

> Use StringUtils trimToEmpty for trimming to avoid NPE
Resolves [product-is #13552](https://github.com/wso2/product-is/issues/13552)

Use StringUtils trimToEmpty for trimming to avoid NPE

---

component/authenticator/pom.xml
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
pom.xml

> Resolves the issue where the sms notification triggered is not being published as expected. 
> The fix will successfully publish the sms notification triggered. 
> Added the notification channel property in the triggered notification event. 
> Trigger sms event publishing notification upon sending the OTP if it is required to use the SMS publisher configuration.
https://github.com/wso2/product-is/issues/13394
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> IS version - 5.10, 5.11
> MacOS
> Chrome, Safari

Smsotp via event publisher improvement

---

component/authenticator/pom.xml
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
pom.xml

A product issue was identified upon trying out the SMS publisher flow with the SMS OTP template added to `<IS_HOME>/repository/conf/sms/sms-templates-admin-config.xml` file. The SMSOTP template is not picked from the above mentioned file and results in the following error. 
```
Error occurred while calling triggerNotification, detail : org.wso2.carbon.identity.governance.exceptions.notiification.NotificationTemplateManagerServerException: Cannot find 'SMSOTP' template in the default 'en_US' locale for 'carbon.super' tenant
```
This behaviour occurs as the SMS channel is not added to the event in the SMS Authenticator. Hence the email template is selected [1] from the handler
[1] https://github.com/wso2-support/identity-event-handler-notification/blob/support-1.3.13.x-full/components/event- …

[3.0.x] Add SMS notification channel to event publisher

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java

> Add additional error logs for `org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.getConnection() ` function.
Issue :  https://github.com/wso2/product-is/issues/14846
> Add debug log for unexpected http response code received.
> If an unexpected http response code is received and debug is enabled, an error log is added with the received http response code.

[U2][5.11.0] Improvement for error logs in SMSOTPAuthenticator.getConnection method

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java

When the `showAuthFailureReason` is set to true, it's expected to show an error message, when the account is locked. This works fine when only the SMS OTP is configured in the second step. However, when it's configured with any other authenticator (ex: Email OTP), it allows the user to try SMS OTP continuously and an error page is not shown.
- https://github.com/wso2/product-is/issues/14868
- https://github.com/wso2/identity-apps/pull/3488

Fix SMS OTP account locked error not shown when configured with multi options

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java

Changes on calculating unlock time and failed login lockout count using temporary context variable.
Related issue: https://github.com/wso2/product-is/issues/14928

[U2] [5.11] Changing failed account lockout and unlock time calculation approach

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java

Related issue: https://github.com/wso2-enterprise/wso2-iam-internal/issues/175
This PR has reverted changes related to account locking. PR: https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/153
The failed login lockout count claim reset logic is shifted to a post authentication handler: https://github.com/wso2-support/carbon-identity-framework/pull/2470

Remove failed login lockout count reset logic

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java

> In a MFA scenario, if a user successfully authenticates a step, the `FailedLoginLockoutCount` claim gets reset. But, there can be authentication failures after a successful authentication in MFA scenarios.
> Resetting the above mentioned claim only for once and it should happen after a complete successful authentication flow.
> Removing the claim reset logic in authenticator level and Introducing a new post authentication handler to reset the claim after a successful authentication flow.
PR for new post authentication handler: https://github.com/wso2-extensions/identity-event-handler-account-lock/pull/119

Remove failed login lockout count claim reset logic

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java

The improvement added with https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/117 was partially reverted with the PR https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/127. Hence adding the replaceAll code blocks again.
Resolves the issue reported in https://github.com/wso2/product-is/issues/13226#issuecomment-1108051913

Fix usage of $ctx.otp

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java

The improvement added with https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/117 was partially reverted with the PR https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/127. Hence adding the replaceAll code blocks again.
Resolves the issue reported in https://github.com/wso2/product-is/issues/13226#issuecomment-1108051913

[4.0.x] Fix issue with ctx.otp

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java

Port the improvement done in https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/117 https://github.com/wso2/product-is/issues/12555 to 3.0.x

[3.0.x] Add support for fully customized SMS with $ctx.otp

---

component/authenticator/pom.xml
pom.xml

This PR bumps the identity governance version to the version where the fix [1] is introduced. It fixes the build failure occurred with [2].
[1] https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.governance/src/main/java/org/wso2/carbon/identity/governance/service/notification/NotificationChannels.java#L32
[2] https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/169

[2.0.x] Update identity governance version

---

component/authenticator/pom.xml
pom.xml

After updating the carbon-identity-framework version in [1], jenkins build is failing with the following error without running tests. Hence, need to bump the kernel version where the `UserStorePreferenceOrderSupplier` is introduced.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project org.wso2.carbon.extension.identity.authenticator.smsotp.connector: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process
[ERROR] java.lang.IllegalStateException: Failed to transform class with name org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils. Reason: org.wso2.carbon.user.core.config.UserStorePreferenceOrderSupplier …
```

[2.0.x] Update kernel version

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/OneTimePassword.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/OnetimePasswordTest.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/constant/Constants.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/util/OneTimePasswordUtils.java
component/common/src/test/java/org/wso2/carbon/identity/smsotp/common/test/OneTimePasswordUtilsTest.java

The default behavior of our products uses SHA1 which is no longer considered as secure. This PR changes the default usage to SHA256 in the following flows.
- Random number will be generated using DRBG algorithm instead of SHA1PRNG.
- OTP will be generated using HMACSHA256.
- Issue https://github.com/wso2/product-is/issues/15793
- PR https://github.com/wso2/carbon-identity-framework/pull/4567
- PR https://github.com/wso2-extensions/identity-outbound-auth-samlsso/pull/162
- PR https://github.com/wso2-extensions/identity-inbound-auth-sts/pull/136
- PR https://github.com/wso2-extensions/identity-metadata-saml2/pull/85
- PR https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2076
- PR https://github.com/wso2/cipher-tool/pull/78
- PR …

Remove SHA1 default usage

---

component/authenticator/pom.xml
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java
pom.xml

Resolves: https://github.com/wso2/product-is/issues/10947
This PR adds support to resolve tenant qualified URL when SMS OTP portal is externalized.
When the tenant qualified URLs feature is enabled
1. If the URL externalized (or customized) is a relative one (ie. hosted within IS with a different context than default), then build the URL with tenant qualified path (/t/{tenantDomain} in the path)
2. If the URL externalized is an absolute one, then we do not try to tenant qualify it.
3. If no URLs are defined from configs, then build the tenant qualified URLs with the default context
Related issue: https://github.com/wso2/product-is/issues/10953

Provided Tenant Qualified URL Support for SMS OTP

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java

SMS OTP and TOTP backup codes are stored in the http://wso2.org/claims/otpbackupcodes claim. Ideally, it should be an identity claim
>Persist backup codes in an identity claim
> Add a deployment.toml configuration to enable treating the backup code claim as an identity claim
* https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/173
*  https://github.com/wso2/carbon-identity-framework/pull/5155
https://github.com/wso2-enterprise/wso2-iam-internal/issues/942
https://github.com/wso2/product-is/issues/17252

Add configuration to handle backup codes as an identity claim

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java

User is currently redirected to an empty page when user does not exist. This fix is to redirect the user to the sms otp error page.
- https://github.com/wso2/product-is/issues/17527
- https://github.com/wso2/identity-apps/pull/4682

Redirect to error page if user does not exist

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
pom.xml

- Skip triggering an SMS OTP verification, when the mobile number was updated by user during the SMS OTP flow at the first login where the mobile number is not previously set. At the moment mobile number was already verified during the SMS OTP verification. So no need to verify it again.
- https://github.com/wso2/product-is/issues/18414
- https://github.com/wso2-extensions/identity-governance/pull/795

Skip triggering mobile number verification during SMS OTP flow

---

component/authenticator/pom.xml

Fix runtime import failure that happens when framework version is bumped into 7.x.x
Related to https://github.com/wso2/product-is/issues/19176

Fix runtime import failure

---

docs/sms_otp_service.md

Remove the `webhhok.site` URL from the SMS publisher and added a description instead.

doc update

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java

> In the SMSOTPAuthenticator, the authenticator name is retrieved through the authenticators of the current step. This has caused inconsistencies when both emailOTP and smsOTP are configured in the same step. However inside the SMSOTPAuthenticator class it is not necessary to read the authenticator name through current step since the authenticator is itself. 
This PR fixes this issue by retrieving the name of the authenticator by its own `getName()` function. 
https://github.com/wso2/product-is/issues/19482

Get authenticator name through its own function.

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java

> In the SMSOTPAuthenticator, the authenticator name is retrieved through the authenticators of the current step. This has caused inconsistencies when both emailOTP and smsOTP are configured in the same step. However inside the SMSOTPAuthenticator class it is not necessary to read the authenticator name through current step since the authenticator is itself. 
This PR fixes this issue by retrieving the name of the authenticator by its own `getName()` function. 
https://github.com/wso2/product-is/issues/19482

Get authenticator name through own function.

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java

Fixes the issue of not having the display name property in the auth initiation data during api based autehntication.
Related issue: https://github.com/wso2/product-is/issues/20219

Set missing display name property to Auth Initiation Data

---

component/authenticator/pom.xml
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPUtils.java

$subject
Regex can be provided as follows;
```
[authentication.authenticator.sms_otp.parameters]
screenUserAttribute = "http://wso2.org/claims/mobile"
screenUserAttributeMaskRegex='(?&lt;=\d{2})\d(?=\d{2})'
```
Output (If the mobile number is configured as +94776565656):
- https://github.com/wso2/product-is/issues/20221
- https://github.com/wso2/product-is/issues/20415

Implement mobile number masking capability with a regex

---

component/common/pom.xml
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/SMSOTPServiceImpl.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/constant/Constants.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/dto/ConfigsDTO.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/internal/SMSOTPServiceComponent.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/internal/SMSOTPServiceDataHolder.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/util/Utils.java
docs/sms_otp_service.md

Locking the account on failed attempts is made configurable via deployment.toml file as shown in the example below.
```
[[event_handler]]
name= "smsOtp"
properties.enabled=true
properties.lockAccountOnFailedAttempts = true
```
In addition to this, at tenant level it is required to enable the account lock capability and configure other properties such as unlock time duration etc (https://is.docs.wso2.com/en/5.11.0/learn/account-locking-by-failed-login-attempts/#configuring-wso2-is-for-account-locking).

Add account lock capability to SMS OTP Service

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java

- If IDF resolved the user from multi attribute login user resolving service, the `isUserResolved` property is set to true.
- This improvement is done to avoid user resolving again from the user store when the user is already resolved from the previous step.
- From this new changes, we only check for user when there is not `isUserResolved` in the context.
- https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/162
- https://github.com/wso2/product-is/issues/20466

Checking the user is resolved from a previous step

---

component/common/pom.xml
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/SMSOTPServiceImpl.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/constant/Constants.java
component/common/src/main/java/org/wso2/carbon/identity/smsotp/common/util/Utils.java

Add account lock and disabled validation before OTP generation and validation.

[SMS-OTP] Handle showFailureReason disabled & account lock case in error response

---

component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java
component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPUtils.java
component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPAuthenticatorTest.java
component/authenticator/src/test/java/org/wso2/carbon/identity/authenticator/smsotp/test/SMSOTPUtilsTest.java

This PR will provide the support to validate the resend code attempts in the SMS OTP authenticator.
1. Maximum Resend attempts read from the application-authenticator.xml file
2. Update the context with the current resend code attempts of the user
3. Validate the user resend code attempts against the config and terminate the session if it is exceeded.
Also, 
`ResendEnable` config is not honoured in the sms otp resend flow in the BE.
Hence this PR will improve the logic to check the config before continuing the resend code flow in smsotp outbound authenticator.
- https://github.com/wso2/product-is/issues/23890

Add maximum otp resend attempts validation 

---

pom.xml

This PR bumps the carbon identity framework version in the osgi accepted range

Update carbon identity framework version range
